2024-03-03 15:55:43,910 - DEBUG - Using proactor: IocpProactor
2024-03-03 15:55:45,829 - INFO - Nami online | By Dogaix
2024-03-03 15:55:46,073 - INFO - Mensagem recebida: /off2
2024-03-03 15:55:47,086 - INFO - Comando off2 recebido. Thread ID: 1450879699596100628
2024-03-03 15:55:47,086 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<off2() done, defined at c:\Users\dpiro\Desktop\botz\z.py:40> exception=AttributeError("'ChatMessage' object has no attribute 'send_message'")>
Traceback (most recent call last):
  File "c:\Users\dpiro\Desktop\botz\z.py", line 46, in off2
    await message.send_message(message.thread_id, content="oi")
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMessage' object has no attribute 'send_message'
